import { MenuItem } from '../types/menu';

export const menuItems: MenuItem[] = [
  {
    id: '1',
    name: 'Espresso',
    description: 'Strong and bold single shot of espresso',
    price: 3.50,
    image: '/images/espresso.jpg',
    category: 'coffee',
    available: true,
  },
  {
    id: '2',
    name: 'Cappuccino',
    description: 'Espresso with steamed milk and foam',
    price: 4.50,
    image: '/images/cappuccino.jpg',
    category: 'coffee',
    available: true,
  },
  {
    id: '3',
    name: 'Latte',
    description: 'Smooth espresso with velvety steamed milk',
    price: 4.75,
    image: '/images/latte.jpg',
    category: 'coffee',
    available: true,
  },
  {
    id: '4',
    name: 'Croissant',
    description: 'Buttery and flaky French pastry',
    price: 3.25,
    image: '/images/croissant.jpg',
    category: 'pastries',
    available: true,
  },
  {
    id: '5',
    name: 'Chocolate Cake',
    description: 'Rich and moist chocolate pastry',
    price: 5.00,
    image: '/images/chocolate-cake.jpg',
    category: 'pastries',
    available: true,
  },
  {
    id: '6',
    name: 'Club Sandwich',
    description: 'Triple stack with chicken, bacon, and fresh vegetables',
    price: 9.99,
    image: '/images/club-sandwich.jpg',
    category: 'sandwiches',
    available: true,
  },
  {
    id: '7',
    name: 'Orange Juice',
    description: 'Fresh squeezed orange juice',
    price: 4.00,
    image: '/images/orange-juice.jpg',
    category: 'beverages',
    available: true,
  },
  {
    id: '8',
    name: 'Iced Coffee',
    description: 'Chilled coffee with ice and milk',
    price: 3.75,
    image: '/images/iced-coffee.jpg',
    category: 'beverages',
    available: true,
  },
];
